title: "[clvrmnky]"
author: Justin Ranton
url: "https://clvrmnky.github.io"
baseurl: ""
description: >
  Notes on UX, interaction design, AI-assisted prototyping, and code-first
  design systems.

permalink: /:slug.html

theme: no-style-please

theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: true
  lowercase_titles: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
